basePath: /api
host: gloo-api-production.up.railway.app
info:
  contact:
    email: support@gloo.com
    name: API Support
  description: API documentation for Gloo
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gloo API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Returns a simple hello world message
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Hello World endpoint
      tags:
      - root
schemes:
- https
swagger: "2.0"
