basePath: /api
definitions:
  models.BaseResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
      status_code:
        type: integer
      success:
        type: boolean
    type: object
  models.ErrorBadRequestResponse:
    properties:
      data: {}
      message:
        example: Bad Request
        type: string
      status:
        example: error
        type: string
      status_code:
        example: 400
        type: integer
      success:
        example: false
        type: boolean
    type: object
  models.ErrorInternalServerErrorResponse:
    properties:
      data: {}
      message:
        example: Internal Server Error
        type: string
      status:
        example: error
        type: string
      status_code:
        example: 500
        type: integer
      success:
        example: false
        type: boolean
    type: object
  models.ErrorNotFoundResponse:
    properties:
      data: {}
      message:
        example: Not Found
        type: string
      status:
        example: error
        type: string
      status_code:
        example: 404
        type: integer
      success:
        example: false
        type: boolean
    type: object
  models.Recipe:
    properties:
      category:
        example: Chicken
        type: string
      created_by:
        example: '@facu.potti'
        type: string
      description:
        example: A feast for the senses
        type: string
      estimated_time:
        example: 15 minutes
        type: string
      id:
        example: 1
        type: integer
      image_url:
        example: https://example.com/image.png
        type: string
      title:
        example: Chicken Wings
        type: string
      total_comments:
        example: 10
        type: integer
      total_likes:
        example: 20
        type: integer
      total_stars:
        example: 4.5
        type: number
    type: object
  routes.GetAllRecipeResponseData:
    properties:
      category:
        example: Chicken
        type: string
      recipes:
        items:
          $ref: '#/definitions/models.Recipe'
        type: array
      searchParam:
        example: chicken
        type: string
    type: object
host: gloo-api-production.up.railway.app
info:
  contact:
    email: support@gloo.com
    name: API Support
  description: API documentation for Gloo
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gloo API
  version: "1.0"
paths:
  /recipes:
    get:
      consumes:
      - application/json
      description: Get all recipes by search and category
      parameters:
      - description: Search term for recipes
        in: query
        name: searchParam
        type: string
      - description: Category filter for recipes
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved recipes
          schema:
            allOf:
            - $ref: '#/definitions/models.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/routes.GetAllRecipeResponseData'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorBadRequestResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorNotFoundResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorInternalServerErrorResponse'
      summary: Get all recipes
      tags:
      - Recipes
  /recipes/{id}:
    get:
      consumes:
      - application/json
      description: Get a specific recipe by its ID
      parameters:
      - description: Recipe ID
        in: path
        minimum: 1
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved recipe
          schema:
            allOf:
            - $ref: '#/definitions/models.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.Recipe'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorBadRequestResponse'
        "404":
          description: Recipe not found
          schema:
            $ref: '#/definitions/models.ErrorNotFoundResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorInternalServerErrorResponse'
      summary: Get recipe by ID
      tags:
      - Recipes
schemes:
- https
swagger: "2.0"
